num_clients: 10
num_epochs: 1
num_rounds: 100
server_address: "192.168.0.110:5555"
seed: 1234

client:
  cid: 0

dataset:
  dataset_name: 'trashnet'
  partition_type: uniform
  dirichlet_alpha: 0.1 # only used in case of dirichlet partition_type
  batch_size:
    train: 32
    test: 64
  shuffle:
    train: true
    test: false
  testset_size: 0.1

poisoning:
  is_enabled: true # only for trashnet, german_traffic.
  method: "label_flipping" # blurring, occlusion, steganography, label_flipping
  rate: 0.05
  target_cids: [0, 1, 2, 3, 4]

optim_scheduler:
  lr: 0.01
  momentum: 0.9

strategy:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 10
  min_evaluate_clients: 10
  min_available_clients: 10

directory:
  log: "./log"
  figure: "./figure"
  datasets: "./datasets"
  loaders: "./loaders"

mlflow:
  exname: "antivenom"
